apiVersion: v1
kind: Service
metadata:
  namespace: nats
  labels:
    app: nats
  name: nats-svc
spec:
  ports:
  - port: 8222
    name: nats1
    protocol: TCP
    targetPort: 8222
  - port: 4222
    name: nats2
    protocol: TCP
    targetPort: 4222
  selector:
    app: nats
  # type: NodePort
