Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "init.sh"

  config.vm.define "master" do |master|
    master.vm.box_download_insecure = true
    master.vm.box = "bento/ubuntu-20.04"        
    master.vm.network "public_network", ip: "192.168.1.192", bridge: "eno1"
    master.vm.hostname = "master"
    master.vm.provider "virtualbox" do |v|
      v.name = "master"
      v.memory = 4096 
      v.cpus = 2
    end
  end


  config.vm.define "worker2" do |worker2|
    worker2.vm.box_download_insecure = true
    worker2.vm.box = "bento/ubuntu-20.04"        
    worker2.vm.network "public_network", ip: "192.168.1.194", bridge: "eno1"
    worker2.vm.hostname = "worker2"
    worker2.vm.provider "virtualbox" do |v|
      v.name = "worker2"
      v.memory = 1024
      v.cpus = 1
    end
  end


end
