apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: kube-logging
  name: logs-pv
  labels:
    volume: logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/kube_logs
    server: 192.168.1.200
