apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kube-logging
  name: logs-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  selector: 
    matchLabels:
      volume: logs-pv
