Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "../../init.sh"
  config.vm.provision "shell", path: "worker2.sh"

  config.vm.define "worker2" do |worker2|
    worker2.vm.box_download_insecure = true
    worker2.vm.box = "bento/ubuntu-20.04"        
    worker2.vm.network "public_network", ip: "192.168.1.196", bridge: "eno1"
    worker2.vm.hostname = "worker2"
    worker2.vm.provider "virtualbox" do |v|
      v.name = "worker2"
      v.memory = 3060
      v.cpus = 1
    end
  end


end
