Vagrant.configure("2") do |config|
  config.vm.provision "shell", path: "../../init.sh"
  config.vm.provision "shell", path: "worker1.sh"
  

  config.vm.define "worker1" do |worker1|
    worker1.vm.box_download_insecure = true
    worker1.vm.box = "bento/ubuntu-20.04"        
    worker1.vm.network "public_network", ip: "192.168.1.194", bridge: "eno1"
    worker1.vm.hostname = "worker1"
    worker1.vm.provider "virtualbox" do |v|
      v.name = "worker1"
      v.memory = 1024
      v.cpus = 1
    end
  end

end
