apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: mongo
  name: nfs-database-pv
  labels:
    volume: nfs-database-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /mnt/nfs_share
    server: 192.168.1.200
