apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: mongo
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  selector: 
    matchLabels:
      volume: nfs-database-pv
